using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.Experimental.GraphView;
using UPBS.Utility;

namespace UPBS.EditorScripts
{
    //Good reference: https://docs.unity3d.com/ScriptReference/Editor.html
    [CustomEditor(typeof(GeneratePlaybackScene))]
    public class GeneratePlaybackSceneEditor : Editor
    {
        GeneratePlaybackScene sceneGenerator;
        SerializedProperty cosmeticTypesProp, useDerivedClassesProp;
        SerializedProperty autoGeneratedPrefabsProp, autoSaveGeneratedSceneProp, replicationPrecisionProp, sceneSuffixProp, replicateCurrentSceneOnlyProp;
        static GUIContent deleteButtonContent;
        public Color headerColor, bodyColor;

        int listLength;
        private void OnEnable()
        {

            if (sceneGenerator = serializedObject.targetObject as GeneratePlaybackScene)
            {
                Debug.Log("Clear");
            }
            cosmeticTypesProp = serializedObject.FindProperty("replicationTypes");
            useDerivedClassesProp = serializedObject.FindProperty("useDerivedClasses");

            autoGeneratedPrefabsProp = serializedObject.FindProperty("autoGeneratedPrefabs");
            autoSaveGeneratedSceneProp = serializedObject.FindProperty("autoSaveGeneratedScene");
            replicationPrecisionProp = serializedObject.FindProperty("replicationPrecision");
            sceneSuffixProp = serializedObject.FindProperty("sceneSuffix");
            replicateCurrentSceneOnlyProp = serializedObject.FindProperty("replicateCurrentSceneOnly");

            listLength = cosmeticTypesProp.arraySize;
            deleteButtonContent = new GUIContent(EditorGUIUtility.IconContent("P4_DeletedLocal").image); //@2x
        }

        private void AddComponent(System.Type type)
        {
            if (!sceneGenerator.replicationTypes.Contains(new SerializableSystemType(type)))
            {
                sceneGenerator.replicationTypes.Add(new SerializableSystemType(type));
                sceneGenerator.useDerivedClasses.Add(false);
            }

            else
            {
                Debug.LogWarning("Selected class already in the list");
            }
        }

        private void RemoveAt(int index)
        {
            Debug.Log(index);
            sceneGenerator.replicationTypes.RemoveAt(index);
            sceneGenerator.useDerivedClasses.RemoveAt(index);
        }

        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            //headerColor = EditorGUILayout.ColorField(headerColor);
            //bodyColor = EditorGUILayout.ColorField(bodyColor);
            //EditorGUILayout.Space();
            //EditorGUILayout.Space();
            //EditorGUILayout.Space();
            //EditorGUILayout.Space();

            ShowList(cosmeticTypesProp, useDerivedClassesProp);
            
            EditorGUILayout.Space();
            EditorGUILayout.Space();
            EditorGUILayout.PropertyField(autoGeneratedPrefabsProp);
            EditorGUILayout.Space();
            EditorGUILayout.PropertyField(replicationPrecisionProp);
            EditorGUILayout.PropertyField(replicateCurrentSceneOnlyProp);
            EditorGUILayout.PropertyField(autoSaveGeneratedSceneProp);
            if (autoSaveGeneratedSceneProp.boolValue)
            {
                EditorGUILayout.PropertyField(sceneSuffixProp);
            }

            EditorGUILayout.Space();
            EditorGUILayout.Space();
            //EditorGUILayout.Space();
            //EditorGUILayout.Space();

            GeneratePlaybackScene sceneGenerator = (serializedObject.targetObject as GeneratePlaybackScene);
            if (GUILayout.Button(new GUIContent("Generate Playback Scene"), UPBSEditorStyles.UtilityButton))
            {
                //Generate Scene
                sceneGenerator.Generate();
            }

            EditorGUILayout.Space(8);
            //EditorGUILayout.Space();

            GUILayout.Label("Global Generation", UPBSEditorStyles.Header2);

            if (GUILayout.Button(new GUIContent("Set Current As Default"), UPBSEditorStyles.UtilityButton_2))
            {
                sceneGenerator.SetAsDefault();
            }
            using (new EditorGUI.DisabledScope(true))
            {
                EditorGUILayout.ObjectField(GeneratePlaybackScene.DefaultGenerator, typeof(GeneratePlaybackScene), false);
            }

            serializedObject.ApplyModifiedProperties();
        }

        public void ShowList(SerializedProperty cosmeticList, SerializedProperty boolList)
        {
            if (!cosmeticList.isArray)
            {
                EditorGUILayout.HelpBox(cosmeticList.name + " is neither an array nor a list!", MessageType.Error);
                return;
            }

            Color textColor = EditorGUIUtility.isProSkin ? Color.white : Color.black;
            Color originalContentColor = GUI.contentColor;
            using(new EditorGUI.IndentLevelScope(1))
            {
                using (var vertScope = new EditorGUILayout.VerticalScope(new GUIStyle()))
                {
                    
                    EditorGUI.DrawRect(vertScope.rect, EditorGUIUtility.isProSkin ? UPBS.Constants.EDITOR_SECONDARY_BRAND_COLOR_DARK : bodyColor);
                    DrawHorizontalLine(Color.gray, thickness: 1, padding: 0);
                    using (var header = new EditorGUILayout.HorizontalScope())
                    {
                        EditorGUI.DrawRect(header.rect, EditorGUIUtility.isProSkin ? UPBS.Constants.EDITOR_BRAND_COLOR_DARK : headerColor);
                        
                        DrawVerticalLine(Color.gray, 1);
                        GUI.contentColor = textColor;
                        GUILayout.Label("Replication Types", EditorStyles.boldLabel);
                        GUI.contentColor = originalContentColor;
                        DrawVerticalLine(Color.gray, 1);
                    }

                    System.Action RemovalAction = null;
                    if (cosmeticList.arraySize == boolList.arraySize)
                    {
                        DrawHorizontalLine(Color.gray, thickness: 1, padding: 0);
                        for (int i = 0; i < cosmeticList.arraySize; ++i)
                        {
                            using (new EditorGUILayout.HorizontalScope(GUILayout.ExpandWidth(false)))
                            {
                                int x = i;
                                DrawVerticalLine(Color.gray, 1);

                                GUI.contentColor = textColor;
                                EditorGUILayout.PropertyField(cosmeticList.GetArrayElementAtIndex(i), EditorStyles.miniBoldFont);
                                GUI.contentColor = originalContentColor;

                                DrawVerticalLine(Color.gray, 1);
                                EditorGUI.BeginDisabledGroup(i == 0);

                                bool result = GUILayout.Toggle(boolList.GetArrayElementAtIndex(i).boolValue,"", EditorStyles.toggle, GUILayout.MaxWidth(15));
                                if(result != sceneGenerator.useDerivedClasses[i])
                                {
                                    Undo.RecordObject(target, "Changed useDerivedClasses");
                                    sceneGenerator.useDerivedClasses[i] = result;
                                }

                                DrawVerticalLine(Color.gray, 1);
                                if (GUILayout.Button(deleteButtonContent, EditorStyles.miniButton, GUILayout.MaxWidth(70)))
                                {
                                    RemovalAction = () => RemoveAt(x);
                                    Debug.Log("Delete Button Pushed");
                                }
                                DrawVerticalLine(Color.gray, 1);
                                EditorGUI.EndDisabledGroup();
                                //EditorGUILayout.PropertyField(boolList.GetArrayElementAtIndex(i));
                            }
                            
                            DrawHorizontalLine(Color.gray, thickness: 1, padding: 0);
                        }
                    }

                    if (RemovalAction != null)
                    {
                        RemovalAction.Invoke();
                    }
                    using (var addComp = new EditorGUILayout.HorizontalScope())
                    {
                        DrawVerticalLine(Color.gray, 1);

                        if (GUILayout.Button(new GUIContent("Add Reflection Type")))
                        {
                            var searchProvider = CreateInstance<ComponentSearchProvider>();
                            searchProvider.AssignCallback(AddComponent);
                            var searchWindowContext = new SearchWindowContext(GUIUtility.GUIToScreenPoint(Event.current.mousePosition));
                            SearchWindow.Open(searchWindowContext, searchProvider);
                            Debug.Log("Here");
                        }

                        DrawVerticalLine(Color.gray, 1);
                    }

                    DrawHorizontalLine(Color.gray, thickness: 1, padding: 0);

                }
            }
            GUI.contentColor = originalContentColor;

        }

        public static void DrawHorizontalLine(Color color, int thickness = 2, int padding = 10, int xOffset = 0)
        {
            Rect r = EditorGUILayout.GetControlRect(GUILayout.Height(padding + thickness));
            r.height = thickness;
            r.y += padding / 2;
            r.x -= xOffset;
            //r.width += 6;
            EditorGUI.DrawRect(r, color);
        }

        public static void DrawVerticalLine(Color color, int width = 1, int extraHeight = 4, int yOffset = -2, int xOffset = 0)
        {
            Rect r = EditorGUILayout.GetControlRect(GUILayout.Width(width));
            r.height += extraHeight;
            r.y += yOffset;
            r.x += xOffset;
            EditorGUI.DrawRect(r, color);
        }
    }
}